### ISSUE TITLE
Setup appropriate default plugins

### ISSUE THREAD

**Issue by joe-meyer** [ExchangeCore/Concrete5-CKEditor#1]
I just kind of tossed a few in there as an example. We should come up with a reasonable list to attempt to mimic the functionality that redactor provides by default.

See https://github.com/ExchangeCore/Concrete5-CKEditor/blob/master/controller.php#L169-L183

**Comment by MrKarlDilkington** [comment]
I whittled down what I think is a good default set of plugins.

![default_plugins](https://cloud.githubusercontent.com/assets/10898145/10602661/99dacb84-76e7-11e5-9aec-028165dc7f63.png)

``` php
protected function setupDefaultPlugins()
{
    $this->getConfig()->save('plugins',
        array(
            'a11yhelp',
            'basicstyles',
            'blockquote',
            'clipboard',
            'colorbutton',
            'colordialog',
            'contextmenu',
            'dialogadvtab',
            'elementspath',
            'enterkey',
            'entities',
            'floatingspace',
            'font',
            'format',
            'htmlwriter',
            'image',
            'indentblock',
            'indentlist',
            'justify',
            'link',
            'list',
            'liststyle',
            'magicline',
            'removeformat',
            'resize',
            'showblocks',
            'showborders',
            'sourcearea',
            'specialchar',
            'stylescombo',
            'tab',
            'table',
            'tabletools',
            'toolbar',
            'undo',
            'wysiwygarea'
        )
    );
}
```

**Comment by joe-meyer** [comment]
This is a pretty solid list.

Do you have any particular love for the blockquote / specialchar functionality? At a glance I'm not sure I see blockquote being used much by my basic users, ditto for the symbols stuff. With it being so easy to turn on I feel more inclined to strip this down as far as possible and let people build it back up to their liking. 

I don't feel very strongly about this either way but anything we can do to dwindle down options to eliminate confusion seems ideal to me.

**Comment by MrKarlDilkington** [comment]
You are right, those two aren't essential.

Last night I tried to remove the copy, paste, and cut, but didn't realize it was "Clipboard".

![default_plugins](https://cloud.githubusercontent.com/assets/10898145/10622455/b497fdd4-7755-11e5-94e8-2760af2a1dd5.png)

``` php
protected function setupDefaultPlugins()
{
    $this->getConfig()->save('plugins',
        array(
            'a11yhelp',
            'basicstyles',
            'colorbutton',
            'colordialog',
            'contextmenu',
            'dialogadvtab',
            'elementspath',
            'enterkey',
            'entities',
            'find',
            'floatingspace',
            'font',
            'format',
            'htmlwriter',
            'image',
            'indentblock',
            'indentlist',
            'justify',
            'link',
            'list',
            'liststyle',
            'magicline',
            'removeformat',
            'resize',
            'showblocks',
            'showborders',
            'sourcearea',
            'stylescombo',
            'tab',
            'table',
            'tabletools',
            'toolbar',
            'undo',
            'wysiwygarea'
        )
    );
}
```

**Comment by joe-meyer** [comment]
Ok i'm closing this per https://github.com/ExchangeCore/Concrete5-CKEditor/commit/58c1621792a95073371681ed62aeac2ae943097b we can always revisit later if necessary
