### ISSUE TITLE
Source Editing Area plugin doesn't work in the Content Block

### ISSUE THREAD

**Issue by MrKarlDilkington** [ExchangeCore/Concrete5-CKEditor#15]
I found out why the Source Editing Area plugin (code view) doesn't work in the Content Block.

It turns out you need an additional plugin (Source Dialog) to make it work.

http://ckeditor.com/addon/sourcearea
"Source Editing Area

This plugin adds the source editing mode to CKEditor. It allows you to modify the editor output in the HTML format.

**Note: If you want to show the editor source in inline editor, install the Source Dialog plugin**. If another plugin generates editor output data format other than HTML, like e.g. the BBCode plugin, the source editing area will display that format."

Source Dialog plugin page:
http://ckeditor.com/addon/sourcedialog

**Comment by joe-meyer** [comment]
Completed fbb834c3f9253e6fb2a4f691a1cb8703d04a5894
