### ISSUE TITLE
Switch to Div Editing Area instead of IFrame Editing Area

### ISSUE THREAD

**Issue by MrKarlDilkington** [ExchangeCore/Concrete5-CKEditor#16]
It turns out that IFrame Editing Area is the default for CKEditor. This prevents page CSS from applying to content in the CKEditor. Using Div Editing Area will allow CSS styles to "pass through" to editor content.

The Content block editing area isn't in an iframe. The editing area in blocks and in Composer does use an iframe.

IFrame Editing Area versus Div Editing Area:

"IFrame Editing Area

This plugin represents an editing area that stores the editor content inside of an embedded iframe, so that content styles were not inherited from the host page."

"Div Editing Area

This plugin uses a div element (instead of the traditional iframe element) as the editable area in the themedui creator. Much similar to inline editing, it benefits from allowing the editor content to inherit from host page styles."

Demo of the Div Editing Area:
http://ckeditor.com/demo#div

Div Editing Area plugin page:
http://ckeditor.com/addon/divarea

**Comment by joe-meyer** [comment]
We need to make sure we aren't breaking other plugin dependencies by doing this since many of them may be dependent on the iframe. I'll give this a shot and see what happens.

**Comment by joe-meyer** [comment]
I'm also wondering if the stylesheet parser plugin you proposed would have any effect on this?

**Comment by MrKarlDilkington** [comment]
In the Div Editing Area demo, the plugins all appear to work the same way.

The plugin description doesn't include any special instructions or warnings about iframe dependencies, so I am making an assumption that it shouldn't affect anything.

**Comment by joe-meyer** [comment]
Completed in c7f766f0e0fca67426b887d5de895232bef4975c
