### ISSUE TITLE
Implement concrete5magic functionality

### ISSUE THREAD

**Issue by MrKarlDilkington** [ExchangeCore/Concrete5-CKEditor#19]
Here is a quick idea.

What about a dashboard page where the custom styles could be pasted into a text area (or Ace Editor with JSON syntax checking enabled). 

On save the styles are wrapped in the following code required for CKEditor, styles.js is opened and its contents are replaced with the combined CKEditor code and custom styles.

```
CKEDITOR.stylesSet.add( 'default', [

] );
```

![styles_dashboard_page](https://cloud.githubusercontent.com/assets/10898145/10714792/c653ddfe-7ad4-11e5-8ea5-d5e979b06837.png)

**Comment by joe-meyer** [comment]
I agree we should have a dashboard page to do more advanced configuration, I don't agree it should be using JSON format. I think we should shoot for a more strict, and user friendly approach. If someone wants to build it out in JSON it's easy enough for someone to build a plugin to do just that.

**Comment by MrKarlDilkington** [comment]
I only included the JSON part because that is what the custom styles format appears to be in styles.js.

**Comment by joe-meyer** [comment]
Actually, could we just use the same stuff that the redactor [concrete5magic](https://github.com/concrete5/concrete5/blob/5.7.5.2/web/concrete/js/build/core/redactor/magic.js#L30-L74) plugin uses for these?

**Comment by MrKarlDilkington** [comment]
@joe-meyer 

I think using the existing concrete5magic to add custom styles is a good idea and better than storing styles in a dashboard page.

**Comment by joe-meyer** [comment]
Ok... I think that we definitely need to implement the concrete5magic stuff into ckeditor. I think that'll get us up to where we need to be to match existing redactor functionality (and then some). Perhaps a little later we'll work on a dashboard page for further configuration.

**Comment by joe-meyer** [comment]
Currently stuck: http://stackoverflow.com/questions/33829939/ckeditor-insert-non-editable-html-within-style

**Comment by MrKarlDilkington** [comment]
I tested the latest magicstyles branch with the dedicated CKEditor Styles page. Adding styles this way worked as expected and gets the job done.

For an initial release, I think a basic textarea for input is sufficient.

**Comment by joe-meyer** [comment]
finished implementing via 1fdfb5ab7808a7bc2e3ddffa05a1fb182809c068

more accurately 17c72d127643f5308bad72639c940f3eea0b6d7d
