### ISSUE TITLE
Codesnippet plugin doesn't work

### ISSUE THREAD

**Issue by joe-meyer** [ExchangeCore/Concrete5-CKEditor#20]
Currently when you build a code snippet it appears to throw away the line breaks / spacing.

![image](https://cloud.githubusercontent.com/assets/1292766/10721260/35e02b4e-7b77-11e5-943e-f496fd9b73b0.png)

![image](https://cloud.githubusercontent.com/assets/1292766/10721265/4deaf2aa-7b77-11e5-91fc-749630387a7b.png)

**Comment by MrKarlDilkington** [comment]
This is a core bug. 

The same thing happens if you try to use pre tags using Redactor.

**Comment by ChrisHougard** [comment]
Problem is with the HTML DOM Parser (https://github.com/concrete5/concrete5/blob/develop/web/concrete/src/Editor/LinkAbstractor.php#L106)

I remember looking in to this when I was working on a markdown block and not finding a good way to disable the line break removal without getting rid of that library.

**Comment by joe-meyer** [comment]
http://cdn.meme.am/instances/500x/53200814.jpg

**Comment by joe-meyer** [comment]
Opened issue https://github.com/concrete5/concrete5/issues/3063

**Comment by joe-meyer** [comment]
Also, it doesn't appear like we're loading up highlight.js.

**Comment by joe-meyer** [comment]
Chris and I were talking some about this plugin in particular. I'm thinking that the code snippet plugin is probably something that we'll want to take out of the community_editor package because it has view dependencies (js / css files) in addition to the editor stuff which is probably grounds for it's own package. We'll work on coming up with a contributing guideline that spells out what kind of plugins we're willing to add to this repository and what ones we want to avoid.

**Comment by MrKarlDilkington** [comment]
You are right, Code Snippet does seem better suited as a separate package.

**Comment by joe-meyer** [comment]
We need to remove this plugin from this package and then we can close out this issue.

**Comment by joe-meyer** [comment]
This needs to get done before our next release.. I'm bumping the priority to high to make sure it's not forgotten.
