### ISSUE TITLE
Support for responsive images

### ISSUE THREAD

**Issue by MrKarlDilkington** [ExchangeCore/Concrete5-CKEditor#22]
When content is saved in Redactor, images are replaced with responsive picture elements. Having this feature available in CKEditor would be very useful.

**Example:**

_Browser Inspector View - before save_

```
<img id="image-marker" src="http://localhost/concrete5/index.php/download_file/view_inline/111" data-verified="redactor" data-save-url="http://localhost/concrete5/index.php/download_file/view_inline/111">
```

_Browser Inspector View - after save_

```
<picture>
    <!--[if IE 9]><video style='display: none;'><![endif]-->
    <source srcset="http://localhost/concrete5/application/files/7814/4256/0197/GotoChocolateCupcake.png" media="(min-width: 900px)">
    <source srcset="http://localhost/concrete5/application/files/thumbnails/medium/7814/4256/0197/GotoChocolateCupcake.jpg" media="(min-width: 768px)">
    <source srcset="http://localhost/concrete5/application/files/thumbnails/small/7814/4256/0197/GotoChocolateCupcake.jpg">
    <!--[if IE 9]></video><![endif]-->
    <img src="http://localhost/concrete5/application/files/7814/4256/0197/GotoChocolateCupcake.png" alt="#" id="image-marker" style="" width="1024">
</picture>
```

I think the image marker ID, data-verified, and data-save-url attributes are Redactor specific. 
https://github.com/concrete5/concrete5/blob/develop/web/concrete/src/Editor/LinkAbstractor.php#L29

```
private static $blackListImgAttributes = array('src', 'fid', 'data-verified', 'data-save-url');
```

The img to picture replacement appears to be done in LinkAbstractor.
https://github.com/concrete5/concrete5/blob/develop/web/concrete/src/Editor/LinkAbstractor.php

**Comment by joe-meyer** [comment]
Ah I see... we're using `/download_file/view/{ID}` instead of `/download_file/view_inline/{ID}`

**Comment by joe-meyer** [comment]
I also added the alt text from the image title, and set the Link url to be the image's download URL. I'm not sure if the latter is desired or not but I figure it's far easier to remove it when you don't want it than to have to look it up when you do.
