### ISSUE TITLE
Sometimes CKEditor errors after new page load

### ISSUE THREAD

**Issue by joe-meyer** [ExchangeCore/Concrete5-CKEditor#26]
Sometimes, immediately after entering edit mode if you try and edit a content block the editor doesn't come up cleanly. The symptoms appear that the toolbar doesn't appear, if you click inside of the content area the toolbar does appear but most buttons are greyed out
![image](https://cloud.githubusercontent.com/assets/1292766/10818849/fe838a8c-7e1a-11e5-8515-725e5fbfd043.png)
The console is also yelling about an invalid or illegal string being specified. 
![image](https://cloud.githubusercontent.com/assets/1292766/10818871/2cf1c97e-7e1b-11e5-9484-6a408e5745c8.png)
![image](https://cloud.githubusercontent.com/assets/1292766/10818878/38900c32-7e1b-11e5-9e30-dd40076c69d2.png)

We need to track down what's causing this before release.

**Comment by joe-meyer** [comment]
Everything I can seem to find on this seems to indicate browser bug.... Wondering if it's related to chrome developer tools or webkit? Anyone ever have problem with this when they aren't running dev tools?

**Comment by Mesuva** [comment]
I can trigger this issue in Chrome on OSX by repeatedly putting the block into edit mode and out again. I'll do this maybe 8 times and then it'll error as you've described. Sometimes it happens first edit after a page refresh, but sometimes it'll work fine for a few times, then error.  So I'm thinking it's not to do with the initial load of the page in edit mode.

However, my error message is different. Same symptom where I nearly all the buttons are greyed out. Error message as attached.

<img width="945" alt="screen shot 2015-11-18 at 9 07 53 pm" src="https://cloud.githubusercontent.com/assets/1079600/11238970/2d7fe4b0-8e39-11e5-9658-53b9593584d2.png">

I wonder if it's some sort of race condition, where it's trying to load up the content to edit and the editor initializes before the area to edit has been created in the DOM.

**Comment by joe-meyer** [comment]
Wow... Thanks @mesuva, I'm pretty sure you nailed it.... The `querySelectorAll` is apparently known to have problems with identifiers that start with a number. 

I'm going to monitor this for a bit, if anyone else is willing to test it out and report back if they have problems I'd greatly appreciate it.
