### ISSUE TITLE
Plugins can't reliable load from other pacakges

### ISSUE THREAD

**Issue by joe-meyer** [ExchangeCore/Concrete5-CKEditor#29]
In the instance where someone creates a package, and the for that package runs before the ckeditor on_start does, the plugin gets registered against redactor. We need a way to make sure that the new editor loads and can be registered against before our package might necessarily load. Pretty sure this is going to require a core modification.

https://github.com/concrete5/concrete5/issues/3132

**Comment by joe-meyer** [comment]
I'm changing this to be an enhancement. For now we're not officially supporting adding plugins to the editor outside of the package.

**Comment by joe-meyer** [comment]
This isn't a problem, when someone registers a plugin they should use the `on_after_package_start` event in concrete5 to add functionality to an editor

**Comment by tkart38** [comment]
hi 
can make me an example on how to load the ckeditor on other package?
is this possible?
thanks

**Comment by joe-meyer** [comment]
I'm not really planning on making any enhancements to this package or it's documentation since CKEditor is bundled with the core in version 8 and there are many more improvements and documentation examples out there for that now. 

Existing documentation for this v7 version can be found https://docs.exchangecore.com/community_ckeditor/develop/
