### ISSUE TITLE
Integrate filebrowser plugin with Concrete5 File Manager

### ISSUE THREAD

**Issue by joe-meyer** [ExchangeCore/Concrete5-CKEditor#3]
Currently i've commented out the `filebrowser` plugin so that it doesn't get used. Ideally this should hook into the concrete5 file maanger.

**Comment by Mesuva** [comment]
The main question I have with this is whether the concrete5 hooks that expose the file manager functionality to the redactor plugin are generic, or whether they are specifically built for redactor. In other words, is it just emulating the redactor plugin but in ckeditor format, or will it also require creating new functions on the server side.  

(perhaps this is more of a question for the sitemap/link dialog)

**Comment by joe-meyer** [comment]
no new functions server side should need to exist. They did a decent job with separating those out if I recall, it's just a matter of firing the right js events and setting appropriate callbacks I believe. Same for sitemap / link.

**Comment by joe-meyer** [comment]
This has been Implemented

**Comment by Mesuva** [comment]
Nice one!  I had a quick look the other day at what is required, but you're powering on!
