### ISSUE TITLE
Create a way to add Styles

### ISSUE THREAD

**Issue by joe-meyer** [ExchangeCore/Concrete5-CKEditor#30]
We should create a way (Either via dashboard page, or via plugin) to easily add additional [styles](http://docs.ckeditor.com/#!/guide/dev_howtos_styles) to the editor. 

Some possible Options:
## A dashboard page

We would probably want this to be user friendly, maybe we could leverage the same kinds of tools that are available for the theme customizer to build out JSON strings to inject into the list of styles.

This has the benefits of being modifyable via a user interface so semi-technical people can create their own styles, it also has the advantage of allowing us to load up all the styles when the editor is loaded.
## A PHP API that developers could create concrete5 packages and add to

This one is going to be kind of a pain to do but one could possibly do something like this:

```
$editor = Core::make('editor);
if ($editor instanceof CKEditor) {
    $editor->addStyle(array(
        'name' => t('Responsive Image');
        'element' => 'span',
        'attributes' => array('class' => 'img-responsive'),
    ));
}
```

This has the benefit of us still being able to load all the styles at the start of ckeditor, and it provides a super easy way for someone to create a concrete5 package that adds styles to the editor without additional ckeditor plugin registrations / file loading / editor plugin implementation. 
## Force developers to implement their own plugins

This is the current option, we do nothing and developers need to register their own ckeditor plugins that add styles (similar to how we're doing it in our concrete5magic plugin that's in the works). This has the benefit of us never having to touch it, but the major drawback is that every plugin that gets added is going to be 2 more network requests (maybe not a big deal with caching and such?). Regardless if we implement something for the other 2, this will always be an option for developers (so long as ckeditor allows us to inject styles after load).

**Comment by MrKarlDilkington** [comment]
I tested the latest magicstyles branch with the dedicated CKEditor Styles page. Adding styles this way worked as expected and gets the job done.

For an initial release, I think a basic textarea for input is sufficient.

**Comment by joe-meyer** [comment]
I'm closing this via f04fc4aaa3022c54619c3cd5f166f3b17c9648ca 

We can enhance this later for a more user friendly interface.
