### ISSUE TITLE
CKEditor throws away formatting if it doesn't have a plugin for it

### ISSUE THREAD

**Issue by joe-meyer** [ExchangeCore/Concrete5-CKEditor#4]
I'm not sure if this is by design or if there's any way to get around it but I could see it becoming an issue. I think that if there's already html for something, it should leave it there and one should need to re-format it to get rid of the formatting. 

Right now if you take a block that was heavily modified in redactor, open it in ckeditor there's a good chance you're going to lose a lot of the existing styling. I'm not sure that we want this. Also, if you do some styling (say using the `justify` plugin) and then you take that plugin of, and you go and edit the content again, you're styling will disappear.

Anyone have any thoughts on how we can fix this or is this just going to be a "feature"?

**Comment by andyjenx** [comment]
Hi Joe,  I think this is at least partially configurable using CKeditor's Advanced Content Filter which can be configured variously and even switched off:  config.allowedContent = true;.  There are different configurations and some docs at:  http://docs.ckeditor.com/#!/guide/dev_advanced_content_filter.  I might see if I can have a play with the various parts to see how it works in reality.

**Comment by joe-meyer** [comment]
@webcentric that looks about right. Do you have any thoughts on how the editor should behave in reality? On one hand I see the need to customize the html beyond the scope of what the configuration might allow... on the other hand I'm not sure what security vulnerabilities we might be opening up by flipping the switch on this. At a glance it looks like htmLawed seems to be doing some stuff on attributes / Conversation Editor so we'd probably be ok.

I'm sure if needed we could make a "Plugin" that could be turned on / off to flip this setting if needed i'm just not sure what an appropriate default would be.

**Comment by joe-meyer** [comment]
Completed 35b4a0f0b02acd1f698ff27e26d45736c84ff9aa
