### ISSUE TITLE
add Auto Grow plugin for block and Composer editor

### ISSUE THREAD

**Issue by MrKarlDilkington** [ExchangeCore/Concrete5-CKEditor#40]
The current minimum height for the block editor and Composer editor is 200px. When adding content, this causes the editable area to scroll and only a small area available for viewing, requiring the user to drag enlarge the editing area, making content creation and editing slow.

![no-auto-grow](https://cloud.githubusercontent.com/assets/10898145/11916331/6476d166-a6a0-11e5-845a-30008c5c4b9f.png)

An alternative is to add the Auto Grow plugin. This will change the height of the editing area based on the amount of content added.

This link includes a demo:
http://sdk.ckeditor.com/samples/autogrow.html

Redactor and the Content block editor both use auto grow.

**Comment by joe-meyer** [comment]
Added via 256021627151dba3d90d919660c3437f17a59b6c
