### ISSUE TITLE
icon tags in content are hidden during editing

### ISSUE THREAD

**Issue by MrKarlDilkington** [ExchangeCore/Concrete5-CKEditor#48]
The Elemental theme includes icon tags in some page content. An example of this is the "Back to Careers" link on the /team/careers/web-developer and /team/careers/sales-associate pages.

CKEditor hides empty elements while editing from the preview and the source modal.

An internet search pointed to this as a solution: `CKEDITOR.dtd.$removeEmpty['i'] = false`

Example:
packages\community_ckeditor\src\Editor\CKEditor.php

```
        $options = json_encode($options);
        $removeEmptyIcon = '$removeEmpty[\'i\']';
        $html = <<<EOL
        <script type="text/javascript">
        var CCM_EDITOR_SECURITY_TOKEN = "{$this->token}";
        $(function() {
            CKEDITOR.dtd.{$removeEmptyIcon} = false;

            if (CKEDITOR.stylesSet.get('concrete5styles') === null) {
                CKEDITOR.stylesSet.add( 'concrete5styles', {$this->getStylesJson()});
            }
            var ckeditor = $('#{$identifier}').ckeditor({$options}).editor;
            ckeditor.on('blur',function(){
                return false;
            });
            ckeditor.on('remove', function(){
                $(this).destroy();
            });
        });
        </script>
EOL;
```

This appears to work correctly.

**Comment by joe-meyer** [comment]
Would take a PR for this. Also, if you could update the [version 8 branch in the core](https://github.com/concrete5/concrete5/blob/release/8.0.0/web/concrete/src/Editor/CkeditorEditor.php#L78) that'd be helpful too.
