### ISSUE TITLE
z-index: block form > cke link dialog > sitemap dialog

### ISSUE THREAD

**Issue by headland** [ExchangeCore/Concrete5-CKEditor#51]
Thanks for image context menu solution #50!. Now it seems we have a z-index issue: If we use the ckeditor in block form (z-index 1300) and open the link dialog (z-index 10010) and then click on the "Sitemap" button > the sitemap dialog appears but with z-index 1301 and is not reachable. // Toni
![bildschirmfoto 2016-06-06 um 11 58 38](https://cloud.githubusercontent.com/assets/7163669/15818515/19b7a72c-2bde-11e6-9e3d-bf17bf3020e9.png)

**Comment by joe-meyer** [comment]
Bleh..... Thanks. Fixed in https://github.com/ExchangeCore/Concrete5-CKEditor/commit/432ff7d503f9a87bb8007272ba792cd50d592a01

**Comment by headland** [comment]
:-)

**Comment by headland** [comment]
Here my suggestion for a little more stable solution:

(line 22):
jQuery.fn.dialog.open({
                                        width: '90%',
                                        height: '70%',
                                        modal: false,
                                        title: ccmi18n_sitemap.choosePage,
                                        href: CCM_TOOLS_PATH + '/sitemap_search_selector',
                                        **open: function( event, ui ) {
                                            $(this).closest('.ui-dialog').css("zIndex", 10012);
                                        }**
                                    });

**Comment by joe-meyer** [comment]
@headland I'd take a pull request, why the change to 10012 though?

**Comment by headland** [comment]
I didn't test it with 10010. I tried some other solutions and the 12 is a rest of these ...
