### ISSUE TITLE
Need a Package Icon

### ISSUE THREAD

**Issue by joe-meyer** [ExchangeCore/Concrete5-CKEditor#6]
A package Icon that doesn't violate any licensing / copyright needs to be added to the package so we can get it to the PRB.

The package has an icon.  The correct file is a 97x97 transparent .png with a 4px rounded corner named "icon.png". This [psd file](http://www.concrete5.org/download_file/-/view/14175/24758/24758/) can be used as a template. For users of Inkscape and other vector graphics programs, check out this [svg file](http://www.concrete5.org/download_file/-/view/45365/24758/).

**Comment by MrKarlDilkington** [comment]
Here are a couple of ideas.

**the CKEditor logo**
"Can I use your logo in my project?

Yes, but let us know how you intend to use our trademarks by contacting us."
http://ckeditor.com/support/faq/open%20source#question14

**an "edit" icon**
Example: Font Awesome

![edit_icon](https://cloud.githubusercontent.com/assets/10898145/10622920/7064c05e-7758-11e5-91d6-c02bf5da5603.png)

It doesn't have to be this icon exactly, but something that represents "editing".

**Comment by joe-meyer** [comment]
Awesome, I sent CKEditor something to see if we could get permission to use their icon. If they say no we could certainly use something like the edit icon.

**Comment by joe-meyer** [comment]
And the response.

> Re: [##14783##] Contact us form: Other
> 
> Hi Joe,
> 
> Thank you for contacting us.
> Yes of course - feel free to use the attached logo and let us know when it will be ready, so that we can enjoy it too ;)
> Please let me know if you need anything else from us.
> 
> Best regards,
> 
> Wojtek Cichoń
> 
> Community and Customer Support Manager

[CKEditor - Logo.pdf](https://github.com/ExchangeCore/Concrete5-CKEditor/files/17668/CKEditor.-.Logo.pdf)

![ckeditor - logo - big](https://cloud.githubusercontent.com/assets/1292766/10637102/9cc26d62-77d1-11e5-81bc-091688c28037.png)

**Comment by MrKarlDilkington** [comment]
That was a very fast response. They also seem super friendly too.

**icon.png**

![2](https://cloud.githubusercontent.com/assets/10898145/10660065/4a66e3f8-7872-11e5-9d46-3ae43366ea61.png)

**Comment by joe-meyer** [comment]
That icon looks good @MrKarlDilkington would you mind PRing it?

**Comment by joe-meyer** [comment]
Closed via #11
